### ISSUE TITLE
Failing to install when dependencies are met

### ISSUE THREAD

**Issue by VijitSingh97** [bivab/smbus-cffi#16]
I installed all dependencies including cffi and I get this error when running: pip install smbus-cffi

chip@chip:~$ pip install smbus-cffi
Downloading/unpacking smbus-cffi
  Downloading smbus-cffi-0.5.1.tar.gz
  Running setup.py (path:/tmp/pip-build-YUGZZ4/smbus-cffi/setup.py) egg_info for package smbus-cffi
    
    Installed /tmp/pip-build-YUGZZ4/smbus-cffi/cffi-1.10.0-py2.7-linux-armv7l.egg
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-YUGZZ4/smbus-cffi/setup.py", line 48, in <module>
        'Topic :: System :: Hardware',
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__
        _Distribution.__init__(self,attrs)
      File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
        self.finalize_options()
      File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options
        ep.load()(self, ep.name, value)
      File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load
        ['__name__'])
    ImportError: No module named setuptools_ext
    Complete output from command python setup.py egg_info:
    

Installed /tmp/pip-build-YUGZZ4/smbus-cffi/cffi-1.10.0-py2.7-linux-armv7l.egg

Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-YUGZZ4/smbus-cffi/setup.py", line 48, in <module>

    'Topic :: System :: Hardware',

  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup

    _setup_distribution = dist = klass(attrs)

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 266, in __init__

    _Distribution.__init__(self,attrs)

  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__

    self.finalize_options()

  File "/usr/lib/python2.7/dist-packages/setuptools/dist.py", line 301, in finalize_options

    ep.load()(self, ep.name, value)

  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2190, in load

    ['__name__'])

ImportError: No module named setuptools_ext

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-YUGZZ4/smbus-cffi
Storing debug log for failure in /home/chip/.pip/pip.log
chip@chip:~$

**Comment by VijitSingh97** [comment]
Resolved by: sudo pip install cffi --upgrade
